### ISSUE TITLE
RIKEN FANTOM5, and various CSV files outputted from analysing clusters

### ISSUE THREAD

**Issue by erthrall** [shengqh/Hurley2022scRNA#3]
Hi again, I have a question about inferring receptor-ligand interaction with RIKEN FANTOM5. **Could you give a brief description as to how you carried that out?** There are a lot of atlases and tools, e.g. TET and USCS genome browser, available on [the RIKEN FANTOM5 site](https://fantom.gsc.riken.jp/5/), but it's also not very clear in the paper which data was used to carry out this part of the analysis (e.g. did you use CSV files of initial clusters with Seurat?).

In addition, could you please describe what the `edgeR.sig.csv`, `edgeR.design_matrix.csv`, `edgeR.DE.csv`, and `edgeR.csv` do? I gather that these and the RNK files are the outputs of the `in_clusters` and `between_clusters` parts of the analysis, and the RNK files are analysed using GSEA.

Thank you very much for reading!

**Comment by shengqh** [comment]
I am not sure about the RIKEN FANTOM5 part.

For comparison, edgeR.design_matrix.csv includes design matrix used in edgeR, edgeR.csv includes all genes while edgeR.sig.csv includes significantly differential expressed genes only.

You may look at the code.

https://github.com/shengqh/Hurley2022scRNA/blob/main/seurat_sct_celltype_rename_edgeR_betweenCluster_byCell/result/20220209_edgeR_betweenCluster_byCell.r

**Comment by hongyuenwong** [comment]
Hi erthrall, thanks for your question about RIKEN FANTOM5. Dr. Paula Hurley did the receptor-ligand analysis. I discussed with her and she said she described what she did in the Methods of our manuscript (PMID: 36229464):

"Receptor ligand interactions were inferred using receptor-ligands reported in RIKEN FANTOM5 database. Significantly increased DEGs in clusters 5, 6, and 11 (cancer cells) compared to cluster 12 (benign epithelial cells) were compared to ligands reported in RIKEN FANTOM5 database. The expression of corresponding receptors was assessed in cluster 20 cells."

If you need further clarifications, please feel free to email her: paula.hurley@vumc.org

Thanks,
Hong Yuen

**Comment by erthrall** [comment]
Thank you so much, Hong!

**Comment by hongyuenwong** [comment]
No problem Erthrall, with this I'll close this "Issue" thread. :^)
