### ISSUE TITLE
single-cell data object 

### ISSUE THREAD

**Issue by cathalgking** [shengqh/Hurley2022scRNA#4]
I would like to use the single-cell RNA-seq data from this paper as a 'reference' for cell type label annotation. I see that the data is deposited on GEO but it only seems to be raw data or count matrices. Is there anywhere that I can get an R Seurat object (or python) single-cell object which includes the cell type labels? As shown in figure 1(i).
Thanks

**Comment by shengqh** [comment]
The R object has been uploaded to GEO: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE185344. 

https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE185344&format=file&file=GSE185344%5FPH%5FscRNA%2Efinal%2Erds%2Egz

**Comment by cathalgking** [comment]
I downloaded the object and loaded it into R. However, I don't see the cell type annotations in the R object (Mast cells, Myeloid cells, T cells etc.) as shown in Figure 1 of the paper. Where can I get this info?
<img width="767" alt="Screen Shot 2023-09-02 at 3 28 51 pm" src="https://github.com/shengqh/Hurley2022scRNA/assets/32261323/bb3d2a06-776c-4670-ab27-9a7b5cede5a4">

**Comment by shengqh** [comment]
You can download the meta data from GEO:

https://ftp.ncbi.nlm.nih.gov/geo/series/GSE185nnn/GSE185344/suppl/GSE185344_PH_scRNA.rename_cluster.csv.gz
